services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker 
      POSTGRES_DB: insecticide 
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - 5432:5432


volumes:
  pgdata:
